<?php

/**
 * @file
 * Implements hook_mail() for the event_registration module.
 */

use Drupal\Core\Render\Markup;

/**
 * Implements hook_mail().
 */
function event_registration_mail($key, &$message, $params) {
  switch ($key) {
    case 'user_confirmation':
    case 'admin_notification':
      $message['subject'] = $params['subject'];
      $message['body'][] = Markup::create($params['body']);
      break;
  }
}
